[package]
name = "gres"
version = "0.2.1"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2021"

[features]
cli = ["crossterm", "tokio"]

[dependencies]
async-trait = "0.1"

[dependencies.async-proto]
version = "0.15"
optional = true

[dependencies.crossterm]
version = "0.25"
optional = true

[dependencies.serde]
version = "1"
features = ["derive"]
optional = true

[dependencies.tokio]
version = "1"
features = ["sync"]
optional = true
