[package]
name = "gres"
version = "0.1.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2021"

[dependencies]
async-trait = "0.1"

[dependencies.serde]
version = "1"
optional = true
features = ["derive"]
